name: "Release"

on:
  push:
    paths:
      - '.github/workflows/release.yaml'
      - 'Dockerfile'
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/omico/actions-runner
          flavor: |
            latest=true
          tags: |
            type=raw,value={{date 'YYYYMMDD'}}

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: omico
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          provenance: false
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
